-- 2.1
--1
SELECT * FROM EMPLOYEE;
--2
SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';
--3
SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

--2.2
--1
SELECT * FROM ALBUM ORDER BY TITLE DESC;
--2
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

--2.3
--1
INSERT INTO GENRE (GENREID, NAME) VALUES (26, 'Espionage');
INSERT INTO GENRE (GENREID, NAME) VALUES (27, 'Horror');

--2
INSERT INTO EMPLOYEE VALUES (9, 'Bourne', 'Jason', 'Spy', 1, '09-JAN-78', '01-NOV-03', '922 7 ST NW', 'ORLANDO', 'FL', 'UNITED STATES', '32780', '+1 (321) 555-5555', '+1 (321) 555-3333', 'jason@chinookcorp.com');
INSERT INTO EMPLOYEE VALUES (10, 'Stark', 'Tony', 'Engineer', 6, '10-MAR-79', '02-JUN-02', '921 7 ST NW', 'Mountain View', 'CA', 'UNITED STATES', '94039', '+1 (650) 444-4444','+1 (650) 444-2222', 'tony@chinookcorp.com');

--3
INSERT INTO CUSTOMER VALUES (60, 'Potts', 'Pepper', 'Stark Industries', '890 Fifth Avenue', 'New York City', 'NY', 'USA', '10001', '+1 (212) 555-1111', '+1 (212) 878-9090', 'pepper@chinookcorp.com', 4);
INSERT INTO CUSTOMER VALUES (61, 'Howard', 'Terrence', 'Stark Industries', '890 Fifth Avenue', 'New York City', 'NY', 'USA', '10001', '+1 (212) 999-8888','+1 (212) 545-1212', 'howard@chinookcorp.com', 3);

--2.4
--1
UPDATE CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME = 'Walker' WHERE CUSTOMERID = 32;
--2
UPDATE ARTIST SET NAME = 'CCR' WHERE ARTISTID = 76;

--2.5
SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

--2.6
--1
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;
--2
SELECT * FROM EMPLOYEE WHERE HIREDATE BETWEEN '01-JUN-03' AND '01-MAR-04';

--2.7

SELECT * FROM user_cons_columns
WHERE CONSTRAINT_NAME = 'FK_INVOICECUSTOMERID';

SELECT c.CUSTOMERID, i.INVOICEID, i.INVOICELINEID FROM INVOICE c 
INNER JOIN INVOICELINE i ON c.INVOICEID = i.INVOICEID
WHERE c.CUSTOMERID = 32;


SELECT * FROM INVOICE WHERE CUSTOMERID = 32;

DELETE FROM INVOICE WHERE CUSTOMERID = 32;

DELETE FROM CUSTOMER WHERE CUSTOMERID = 32;

SELECT * FROM CUSTOMER WHERE FIRSTNAME = 'Robert' AND LASTNAME='Walker';



--SQL> delete from chd
--  2  where p in (
--  3    select p from par
--  4    where p = 2 );
--
--1 row deleted.
--
--SQL>
--SQL> delete from par where p = 2;

-- 3.1


-- 4.0

-- 7.0
-- 7.1
SELECT i.INVOICEID AS INVOICEID, c.FIRSTNAME AS FIRSTNAME, c.LASTNAME AS LASTNAME
FROM CUSTOMER c
INNER JOIN INVOICE i ON i.CUSTOMERID = c.CUSTOMERID; 

--7.2
SELECT i.INVOICEID AS INVOICEID, c.CUSTOMERID AS CUSTOMERID, c.FIRSTNAME AS FIRSTNAME, c.LASTNAME AS LASTNAME, i.TOTAL AS TOTAL
FROM CUSTOMER c
FULL OUTER JOIN INVOICE i ON i.CUSTOMERID = c.CUSTOMERID; 

-- 7.3

